# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: emailer
  pool: 5
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_IP_ADDR"] %>
  port: 5432

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: emailer
  pool: 5
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_IP_ADDR"] %>
  port: 5432

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: emailer
  pool: 5
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_IP_ADDR"] %>
  port: 5432
